language: node_js
node_js:
  - 10
  - 12
install: npm install
jobs:
  include:
    - stage: test
      script:
        - npm run test
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 12
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
