version: '3.7'
services:
  frontend:
    image: ${APP_NAME}:${RELEASE}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: .
        target: /home/app/frontend
        consistency: consistent
      - type: volume
        source: node_modules
        target: /home/app/frontend/node_modules
volumes:
  # let docker compose handle creation
  node_modules:
